language: java
jdk:
 - openjdk8

branches:
 only:
  - master

# Travis CI Server의 Home
cache:
 directories:
  - '$HOME/.m2/repository'
  - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 완료시 메일 알람
notifications:
 email:
  recipients:
   - tkdrn8578@naver.com

before_install:
 - openssl aes-256-cbc -K $encrypted_1116e8e6e492_key -iv $encrypted_1116e8e6e492_iv -in ./src/main/resources/application.yml.enc -out ./src/main/resources/application.yml -d
 - openssl aes-256-cbc -K $encrypted_1116e8e6e492_key -iv $encrypted_1116e8e6e492_iv -in ./src/test/resources/application.yml.enc -out ./src/test/resources/application.yml -d
