spring:
  datasource:
    url: jdbc:mariadb://reuse-rds.crv7hmzovanp.ap-northeast-2.rds.amazonaws.com:3306/reuse
    username: root
    password: qw12er45$%
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

cloud:
  aws:
    s3:
      bucket: reuse-s3
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instanceProfile: true


server:
  port: 6000
