spring:
  datasource:
    url: jdbc:mariadb://reuse-rds.crv7hmzovanp.ap-northeast-2.rds.amazonaws.com:3306/reuse
    username: root
    password: qw12er45$%
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true


server:
  port: 6000
